Iniciar sesión en Kaggle por primera vez puede ser intimidante. Nuestras competencias a menudo tienen grandes premios en efectivo, tablas de clasificación públicas e involucran datos complejos. Sin embargo, realmente creemos que todos los científicos de datos pueden aprender rápidamente de las competencias de aprendizaje automático y contribuir significativamente a nuestra comunidad. Para darle una comprensión clara de cómo funciona nuestra plataforma y un modelo mental del tipo de aprendizaje que podría hacer en Kaggle, hemos creado un tutorial de Introducción para la competencia del Titanic. Lo guía a través de los pasos iniciales requeridos para obtener su primera presentación decente en la tabla de clasificación. Al final del tutorial, también tendrá una comprensión sólida de cómo usar el entorno de codificación en línea de Kaggle, donde habrá entrenado su propio modelo de aprendizaje automático.

Así que si esta es tu primera vez participando en una competencia de Kaggle, independientemente de si:
- tienes experiencia manejando grandes conjuntos de datos,
- no has programado mucho,
- eres nuevo en la ciencia de datos, o
- eres relativamente experimentado (pero simplemente no estás familiarizado con la plataforma de Kaggle),

¡estás en el lugar correcto! 

# Parte 1: Comenzar

En esta sección, aprenderás más sobre la competencia y harás tu primera presentación. 

## ¡Únete a la competencia!

¡Lo primero que debes hacer es unirte a la competencia! Abre una nueva ventana con **[la página de la competencia](https://www.kaggle.com/c/titanic)**, y haz clic en el botón **"Join Competition"** (Unirse a la Competencia), si aún no lo has hecho. (_Si ves un botón "Submit Predictions" (Enviar Predicciones) en lugar de un botón "Join Competition", ya te has unido a la competencia y no necesitas hacerlo nuevamente._)

![](https://i.imgur.com/07cskyU.png)

Esto te lleva a la página de aceptación de reglas. Debes aceptar las reglas de la competencia para poder participar. Estas reglas rigen cuántas presentaciones puedes hacer por día, el tamaño máximo del equipo y otros detalles específicos de la competencia. Luego, haz clic en **"I Understand and Accept"** (Entiendo y Acepto) para indicar que cumplirás con las reglas de la competencia.

## El desafío

La competencia es simple: queremos que uses los datos de los pasajeros del Titanic (nombre, edad, precio del boleto, etc.) para intentar predecir quién sobrevivirá y quién morirá.

## Los datos

Para echar un vistazo a los datos de la competencia, haz clic en la **<a href="https://www.kaggle.com/c/titanic/data" target="_blank" rel="noopener noreferrer"><b>pestaña Data</b></a>** (Datos) en la parte superior de la página de la competencia. Luego, desplázate hacia abajo para encontrar la lista de archivos.  
Hay tres archivos en los datos: (1) **train.csv**, (2) **test.csv**, y (3) **gender_submission.csv**.

### (1) train.csv

**train.csv** contiene los detalles de un subconjunto de los pasajeros a bordo (891 pasajeros, para ser exactos -- donde cada pasajero obtiene una fila diferente en la tabla). Para investigar estos datos, haz clic en el nombre del archivo a la izquierda de la pantalla. Una vez que hayas hecho esto, puedes ver todos los datos en la ventana.  

![](https://i.imgur.com/cYsdt0n.png)

Los valores en la segunda columna (**"Survived"** - Sobrevivió) se pueden usar para determinar si cada pasajero sobrevivió o no: 
- si es un "1", el pasajero sobrevivió.
- si es un "0", el pasajero murió.

Por ejemplo, el primer pasajero listado en **train.csv** es el Sr. Owen Harris Braund. Tenía 22 años cuando murió en el Titanic.

### (2) test.csv

Usando los patrones que encuentres en **train.csv**, debes predecir si los otros 418 pasajeros a bordo (en **test.csv**) sobrevivieron.  

Haz clic en **test.csv** (a la izquierda de la pantalla) para examinar su contenido. Ten en cuenta que **test.csv** no tiene una columna **"Survived"** - esta información está oculta para ti, ¡y qué tan bien lo hagas al predecir estos valores ocultos determinará qué tan alto puntúes en la competencia! 

### (3) gender_submission.csv

El archivo **gender_submission.csv** se proporciona como un ejemplo que muestra cómo debes estructurar tus predicciones. Predice que todas las pasajeras mujeres sobrevivieron, y todos los pasajeros hombres murieron. Tus hipótesis con respecto a la supervivencia probablemente serán diferentes, lo que conducirá a un archivo de presentación diferente. Pero, al igual que este archivo, tu presentación debe tener:
- una columna **"PassengerId"** que contenga los IDs de cada pasajero de **test.csv**.
- una columna **"Survived"** (¡que crearás!) con un "1" para las filas donde crees que el pasajero sobrevivió, y un "0" donde predices que el pasajero murió.

# Parte 2: Tu entorno de codificación

En esta sección, entrenarás tu propio modelo de aprendizaje automático para mejorar tus predicciones. _Si nunca has escrito código antes o no tienes experiencia con el aprendizaje automático, ¡no te preocupes! No asumimos ninguna experiencia previa en este tutorial._

## El Notebook

Lo primero que debes hacer es crear un Notebook de Kaggle donde almacenarás todo tu código. Puedes usar Kaggle Notebooks para empezar a escribir código rápidamente, y sin tener que instalar nada en tu computadora. (_¡Si estás interesado en el aprendizaje profundo, también ofrecemos acceso gratuito a GPU!_) 

Comienza haciendo clic en la **<a href="https://www.kaggle.com/c/titanic/kernels" target="_blank">pestaña Code</a>** (Código) en la página de la competencia. Luego, haz clic en **"New Notebook"** (Nuevo Notebook).

![](https://i.imgur.com/v2i82Xd.png)

Tu notebook tardará unos segundos en cargarse. En la esquina superior izquierda, puedes ver el nombre de tu notebook -- algo como **"kernel2daed3cd79"**.

![](https://i.imgur.com/64ZFT1L.png)

Puedes editar el nombre haciendo clic en él. Cámbialo a algo más descriptivo, como **"Comenzando con Titanic"**.  

![](https://i.imgur.com/uwyvzXq.png)

## Tus primeras líneas de código

Cuando inicias un nuevo notebook, tiene dos cuadros grises para almacenar código. Nos referimos a estos cuadros grises como "celdas de código".

![](https://i.imgur.com/q9mwkZM.png)

La primera celda de código ya tiene algo de código en ella. Para ejecutar este código, coloca tu cursor en la celda de código. (_Si tu cursor está en el lugar correcto, notarás una línea vertical azul a la izquierda del cuadro gris._) Luego, presiona el botón de reproducción (que aparece a la izquierda de la línea azul), o presiona **[Shift] + [Enter]** en tu teclado.

Si el código se ejecuta correctamente, se devuelven tres líneas de salida. A continuación, puedes ver el mismo código que acabas de ejecutar, junto con la salida que deberías ver en tu notebook.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('./'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

./gender_submission.csv
./test.csv
./titanic-tutorial.ipynb
./train.csv

Esto nos muestra dónde se almacenan los datos de la competencia, para que podamos cargar los archivos en el notebook. Haremos eso a continuación.

## Cargar los datos

La segunda celda de código en tu notebook ahora aparece debajo de las tres líneas de salida con las ubicaciones de los archivos.

![](https://i.imgur.com/OQBax9n.png)

Escribe las dos líneas de código a continuación en tu segunda celda de código. Luego, una vez que hayas terminado, haz clic en el botón azul de reproducción, o presiona **[Shift] + [Enter]**.

In [2]:
train_data = pd.read_csv("./train.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Tu código debería devolver la salida anterior, que corresponde a las primeras cinco filas de la tabla en **train.csv**. ¡Es muy importante que veas esta salida **en tu notebook** antes de continuar con el tutorial!
> _Si tu código no produce esta salida_, verifica que tu código sea idéntico a las dos líneas anteriores. Y asegúrate de que tu cursor esté en la celda de código antes de presionar **[Shift] + [Enter]**.

El código que acabas de escribir está en el lenguaje de programación Python. Utiliza un "módulo" de Python llamado **pandas** (abreviado como `pd`) para cargar la tabla del archivo **train.csv** en el notebook. Para hacer esto, necesitábamos conectar la ubicación del archivo (que vimos que era `./train.csv`).  
> Si aún no estás familiarizado con Python (y pandas), el código no debería tener sentido para ti -- ¡pero no te preocupes! El punto de este tutorial es (¡rápidamente!) hacer tu primera presentación a la competencia. Al final del tutorial, sugerimos recursos para continuar tu aprendizaje.

En este punto, deberías tener al menos tres celdas de código en tu notebook.  
![](https://i.imgur.com/ReLhYca.png)

Copia el código a continuación en la tercera celda de código de tu notebook para cargar el contenido del archivo **test.csv**. ¡No olvides hacer clic en el botón de reproducción (o presionar **[Shift] + [Enter]**)!

In [3]:
test_data = pd.read_csv("./test.csv")
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Como antes, asegúrate de ver la salida anterior en tu notebook antes de continuar.  

Una vez que todo el código se ejecute correctamente, todos los datos (en **train.csv** y **test.csv**) se cargan en el notebook. (_El código anterior muestra solo las primeras 5 filas de cada tabla, ¡pero todos los datos están ahí -- todas las 891 filas de **train.csv** y todas las 418 filas de **test.csv**!_)

Data Dictionary
Variable	Definition	Key
survival	Survival	0 = No, 1 = Yes
pclass	Ticket class	1 = 1st, 2 = 2nd, 3 = 3rd
sex	Sex	
Age	Age in years	
sibsp	# of siblings / spouses aboard the Titanic	
parch	# of parents / children aboard the Titanic	
ticket	Ticket number	
fare	Passenger fare	
cabin	Cabin number	
embarked	Port of Embarkation	C = Cherbourg, Q = Queenstown, S = Southampton
Variable Notes
pclass: A proxy for socio-economic status (SES)
1st = Upper
2nd = Middle
3rd = Lower

age: Age is fractional if less than 1. If the age is estimated, is it in the form of xx.5

sibsp: The dataset defines family relations in this way...
Sibling = brother, sister, stepbrother, stepsister
Spouse = husband, wife (mistresses and fiancés were ignored)

parch: The dataset defines family relations in this way...
Parent = mother, father
Child = daughter, son, stepdaughter, stepson
Some children travelled only with a nanny, therefore parch=0 for them.

# Parte 3: Tu primera presentación

Recuerda nuestro objetivo: queremos encontrar patrones en **train.csv** que nos ayuden a predecir si los pasajeros en **test.csv** sobrevivieron.

Inicialmente puede parecer abrumador buscar patrones, cuando hay tantos datos para ordenar. Así que comenzaremos de manera simple.

## Explorar un patrón

Recuerda que el archivo de presentación de muestra en **gender_submission.csv** asume que todas las pasajeras mujeres sobrevivieron (y todos los pasajeros hombres murieron).  

¿Es esta una primera suposición razonable? Verificaremos si este patrón se mantiene verdadero en los datos (en **train.csv**).

Copia el código a continuación en una nueva celda de código. Luego, ejecuta la celda.

In [4]:
women = train_data.loc[train_data.Sex == 'female']["Survived"]
rate_women = sum(women)/len(women)

print("% de mujeres que sobrevivieron:", rate_women)

% de mujeres que sobrevivieron: 0.7420382165605095

Antes de continuar, asegúrate de que tu código devuelva la salida anterior. El código anterior calcula el porcentaje de pasajeras mujeres (en **train.csv**) que sobrevivieron.

Luego, ejecuta el código a continuación en otra celda de código:

In [5]:
men = train_data.loc[train_data.Sex == 'male']["Survived"]
rate_men = sum(men)/len(men)

print("% de hombres que sobrevivieron:", rate_men)

% de hombres que sobrevivieron: 0.18890814558058924

El código anterior calcula el porcentaje de pasajeros hombres (en **train.csv**) que sobrevivieron.

A partir de esto puedes ver que casi el 75% de las mujeres a bordo sobrevivieron, mientras que solo el 19% de los hombres vivieron para contarlo. Dado que el género parece ser un indicador tan fuerte de supervivencia, ¡el archivo de presentación en **gender_submission.csv** no es una mala primera suposición!

Pero al final del día, esta presentación basada en género basa sus predicciones en solo una única columna. Como puedes imaginar, al considerar múltiples columnas, podemos descubrir patrones más complejos que potencialmente pueden generar predicciones mejor informadas. Dado que es bastante difícil considerar varias columnas a la vez (o, tomaría mucho tiempo considerar todos los posibles patrones en muchas columnas diferentes simultáneamente), usaremos el aprendizaje automático para automatizar esto por nosotros.

## Tu primer modelo de aprendizaje automático

Construiremos lo que se conoce como un modelo de **bosque aleatorio** (random forest). Este modelo está construido de varios "árboles" (hay tres árboles en la imagen a continuación, ¡pero construiremos 100!) que considerarán individualmente los datos de cada pasajero y votarán sobre si el individuo sobrevivió. Luego, el modelo de bosque aleatorio toma una decisión democrática: ¡el resultado con más votos gana!

![](https://i.imgur.com/AC9Bq63.png)

La celda de código a continuación busca patrones en cuatro columnas diferentes (**"Pclass"**, **"Sex"**, **"SibSp"**, y **"Parch"**) de los datos. Construye los árboles en el modelo de bosque aleatorio basándose en patrones en el archivo **train.csv**, antes de generar predicciones para los pasajeros en **test.csv**. El código también guarda estas nuevas predicciones en un archivo CSV **submission.csv**.

Copia este código en tu notebook, y ejecútalo en una nueva celda de código.

In [ ]:
from sklearn.ensemble import RandomForestClassifier # Importamos el modelo

y = train_data["Survived"] # Etiqueta que queremos predecir

features = ["Pclass", "Sex", "SibSp", "Parch"] # Características que usaremos para predecir si alguien sobrevivió
X = pd.get_dummies(train_data[features]) # Convertimos las variables categóricas en variables dummy/indicadoras
X_test = pd.get_dummies(test_data[features]) # Convertimos las variables categóricas en variables dummy/indicadoras

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1) # Definimos el modelo
# n_estimators es el número de árboles en el bosque, si cambiamos este valor, el modelo puede mejorar o empeorar
# max_depth es la profundidad máxima de cada árbol, si cambiamos este valor, el modelo puede mejorar o empeorar
# random_state es la semilla utilizada por el generador de números aleatorios, si cambiamos este valor, el modelo puede mejorar o empeorar
# La elección de estos valores es un tema complejo que no cubriremos en este tutorial
model.fit(X, y) # Entrenamos el modelo
predictions = model.predict(X_test) # Hacemos predicciones sobre el conjunto de prueba

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions}) # Preparamos el archivo de salida
output.to_csv('submission.csv', index=False) # Guardamos el archivo de salida
print("¡Tu envío fue guardado correctamente!")

¡Tu envío fue guardado correctamente!

Asegúrate de que tu notebook muestre el mismo mensaje ¡Tu presentación se guardó correctamente! antes de continuar.
> ¡Nuevamente, no te preocupes si este código no tiene sentido para ti! Por ahora, nos enfocaremos en cómo generar y enviar predicciones.

Una vez que estés listo, haz clic en el botón **"Save Version"** (Guardar Versión) en la esquina superior derecha de tu notebook. Esto generará una ventana emergente.  
- Asegúrate de que la opción **"Save and Run All"** (Guardar y Ejecutar Todo) esté seleccionada, y luego haz clic en el botón **"Save"** (Guardar).
- Esto genera una ventana en la esquina inferior izquierda del notebook. Después de que haya terminado de ejecutarse, haz clic en el número a la derecha del botón **"Save Version"**. Esto muestra una lista de versiones a la derecha de la pantalla. Haz clic en los puntos suspensivos **(...)** a la derecha de la versión más reciente, y selecciona **Open in Viewer** (Abrir en Visor).  
- Haz clic en la pestaña **Data** (Datos) en la parte superior de la pantalla. Luego, haz clic en el botón **"Submit"** (Enviar) para enviar tus resultados.

![](https://i.imgur.com/1ocaUl4.png)

¡Felicitaciones por hacer tu primera presentación a una competencia de Kaggle! Dentro de diez minutos, deberías recibir un mensaje proporcionando tu posición en la tabla de clasificación. ¡Excelente trabajo!

# Parte 4: ¡Aprende más!

Si estás interesado en aprender más, recomendamos encarecidamente nuestro curso de **[Introducción al Aprendizaje Automático](https://www.kaggle.com/learn/intro-to-machine-learning)** (3 horas), que te ayudará a comprender completamente todo el código que hemos presentado aquí. ¡También sabrás lo suficiente para generar predicciones aún mejores!